spring:
  redis:
    host: 192.168.200.100
    database: 1
    port: 6379
    password: fan123
    lettuce:
      pool:
        max-active: 10
        min-idle: 1
        max-wait: -1
  rabbitmq:
    host: 192.168.200.100
    port: 5672
    username: admin
    password: admin
    virtual-host: /
server:
  port: 8001